export const poGeneralFields = [
  {
    name: "poNumber",
    label: "PO Number",
    type: "text",
    icon: "document-text-outline",
    placeholder: "Enter PO Number",
  },
  {
    name: "date",
    label: "Date",
    type: "text",
    icon: "calendar-outline",
    placeholder: "dd-mm-yyyy",
  },
  {
    name: "poDelivery",
    label: "PO Delivery",
    type: "text",
    icon: "car-outline",
    placeholder: "dd-mm-yyyy",
  },
  {
    name: "requisitionType",
    label: "Requisition Type",
    type: "picker",
    icon: "list-outline",
    options: [
      { label: "Select Requisition Type", value: "Select Requisition Type" },
      { label: "Purchase Requisition", value: "Purchase Requisition" },
      { label: "Store Requisition", value: "Store Requisition" },
    ],
  },
  {
    name: "supplier",
    label: "Supplier",
    type: "text",
    icon: "business-outline",
    placeholder: "Enter Supplier",
  },
  {
    name: "store",
    label: "Store",
    type: "text",
    icon: "storefront-outline",
    placeholder: "Enter Store",
  },
  {
    name: "payment",
    label: "Payment",
    type: "text",
    icon: "card-outline",
    placeholder: "Enter Payment",
  },
  {
    name: "purchaser",
    label: "Purchaser",
    type: "text",
    icon: "person-outline",
    placeholder: "Enter Purchaser",
  },
  {
    name: "remarks",
    label: "Remarks",
    type: "text",
    icon: "chatbox-ellipses-outline",
    placeholder: "Enter Remarks",
  },
];

export const poRowFields = [
  {
    name: "prNo",
    label: "PR No",
    placeholder: "Enter PR No",
    type: "text",
    maxLength: 32,
  },
  {
    name: "department",
    label: "Department",
    placeholder: "Enter Department",
    type: "text",
    maxLength: 32,
  },
  {
    name: "category",
    label: "Category",
    placeholder: "Enter Category",
    type: "text",
    maxLength: 32,
  },
  {
    name: "name",
    label: "Item Name",
    placeholder: "Enter Item Name",
    type: "text",
    maxLength: 32,
  },
  {
    name: "uom",
    label: "UOM",
    placeholder: "Enter UOM",
    type: "text",
    maxLength: 10,
  },
  {
    name: "quantity",
    label: "Quantity",
    placeholder: "Enter Quantity",
    type: "number",
  },
  {
    name: "rate",
    label: "Rate",
    placeholder: "Enter Rate",
    type: "number",
  },
  {
    name: "discountAmount",
    label: "Discount Amount",
    placeholder: "Enter Discount Amount",
    type: "number",
  },
  {
    name: "otherChargesAmount",
    label: "Other Charges Amount",
    placeholder: "Enter Other Charges Amount",
    type: "number",
  },
  {
    name: "rowRemarks",
    label: "Remarks",
    placeholder: "Enter Remarks",
    type: "text",
    maxLength: 150,
  },
];